### ISSUE TITLE
add to rapid?

### ISSUE THREAD

**Issue by abma** [azaremoth/cursed#1]
shall i add cursed to rapid? if so, what tag name to use? tc (as in modinfo.lua)?

**Comment by azaremoth** [comment]
Oh - please. "tc" as tag is fine for me.

KR,
Jan

Am 09.09.2015 um 20:39 schrieb abma:

**Comment by abma** [comment]
done! should work nicely when https://github.com/azaremoth/cursed/pull/2 is merged
