### ISSUE TITLE
InstantLoad doesn't unload nicely additionally, tobool should be used on if "true" customparams

### ISSUE THREAD

**Issue by ForbodingAngel** [azaremoth/cursed#3]
https://github.com/azaremoth/cursed/blob/master/LuaRules/Gadgets/unit_instantload.lua#L1

tobool should be used on the istransportable customparam. At the moment, "true", works while true, does not. tobool should fix that.

Unloading using spring's methods is pretty shoddy. I can't get flood to work in 103 at all. Every spring version has issues with this. I would like to see the gadget handle unloading as well as loading, bypassing spring's transport system altogether (Sort of anyway).

But beyond that, spring's unitdefs have the "cantBeTransported" tag which defaults to false. This should be used instead of having a customparam for it.

I did get it to error out, but I believe that that was due to spring's crappy unloading.

**Comment by ForbodingAngel** [comment]
Oh forgot to mention, this does not work for bos transports at all, but lus transports work fine.

**Comment by ForbodingAngel** [comment]
Error was caused by unloading a few passengers, but not all, moving to another location and trying to pick up or unload more passengers.

**Comment by azaremoth** [comment]
I redid the gadget (called cmd_transporting.lua):
- Mobile transports do flollow tragets now (the meeting point like pick-up was removes)
- Bunker style unloading was included in this gadget (new command)
- Flood unloaded units from the sky will be placed on the ground directly 
- All custom tags were removed. It now uses Springs transportcapacity, loading radius, cantBeTransported and footprintX
